name: Deploy to Live

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy files
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
      with:
        flags: '-avzr --delete'
        options: '--exclude="wp-content/uploads/*" --exclude="wp-content/cache/*"'
        ssh_options: '-p 22'
        src: 'www'
        dest: 'vlad@s15.aiwebhost.com:/testdevwp.ein-des-ein.com'

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"
